services:
  keiko_bot:
    container_name: keiko-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ["python", "./__main__.py"]

  redis:
    image: bitnami/redis:latest
    container_name: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'keiko_redis_data:/bitnami/redis/data'

  mongodb:
    image: mongo:7.0
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - keiko_mongodb_data:/data/db

volumes:
  keiko_redis_data:
  keiko_mongodb_data:
